# Generated by Django 5.1.6 on 2025-03-06 01:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='followasset',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='followasset',
            constraint=models.UniqueConstraint(fields=('user', 'ticker'), name='unique_user_following_ticker'),
        ),
    ]
