# Generated by Django 4.2.16 on 2024-12-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
