# Generated by Django 4.2.16 on 2024-12-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='start_value',
            field=models.DecimalField(decimal_places=0, default=100000, max_digits=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
