# Generated by Django 5.1.6 on 2025-03-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_followasset_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='quantity',
            field=models.DecimalField(decimal_places=6, max_digits=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(decimal_places=6, max_digits=200),
        ),
    ]
