# Generated by Django 4.2.16 on 2024-12-18 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_leagueuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='total_value',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
    ]
