# Generated by Django 5.2 on 2025-04-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_asset_last_updated_asset_previous_close_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
