# Generated by Django 4.2.16 on 2024-12-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_rename_total_value_asset_value_remove_asset_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='is_currency',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_purchase',
            field=models.BooleanField(default=False),
        ),
    ]
