# Generated by Django 5.2 on 2025-04-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_asset_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='previous_close',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=200),
        ),
    ]
