# Generated by Django 5.2 on 2025-05-02 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_asset_previous_close'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StripeSession',
        ),
    ]
