# Generated by Django 4.2.16 on 2024-12-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_asset_total_value_transaction_total_value_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='leagueuser',
            constraint=models.UniqueConstraint(fields=('user', 'league'), name='unique_user_in_league'),
        ),
    ]
