# Generated by Django 4.2.17 on 2025-01-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_leagueuser_unique_user_in_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='num_users',
            field=models.IntegerField(default=0),
        ),
    ]
