# Generated by Django 5.1.5 on 2025-02-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_remove_asset_total_value_remove_portfolio_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=200),
            preserve_default=False,
        ),
    ]
