# Generated by Django 5.1.6 on 2025-02-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_portfolio_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
